apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresqldb-atelier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresqldb-atelier
  template:
    metadata:
      labels:
        app: postgresqldb-atelier
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: atelier
            - name: POSTGRES_PASSWORD
              value: "pass"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          imagePullPolicy: ""
          name: postgresqldb-atelier
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgresqldb-atelier
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgresqldb-atelier