apiVersion: v1
kind: Service
metadata:
  name: service-order
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001
  selector:
    app: service-order

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-order
  template:
    metadata:
      labels:
        app: service-order
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-atelier
            - name: POSTGRES_DB
              value: atelier
            - name: POSTGRES_PASSWORD
              value: "pass"
            - name: POSTGRES_USER
              value: postgres
          image: kanada3000/service-order
          name: service-order
          ports:
            - name: http
              containerPort: 8081

---